name: Main Branch Logs

on:
  push:
    branches:
      - main

jobs:
  log_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create log
        run: |
          git log --pretty=format:"%h - %an, %ar : %s" --abbrev-commit >> changes.log

      - name: Commit and push changes
        run: |
          git config --local user.email "hidaytrahman@gmail.com"
          git config --local user.name "Hidayt Rahman"
          git add changes.log
          git commit -m "Add changes log for main branch"
          git push
