name: "Manual Trigger Deployment"

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose Environments'     
        required: true
        default: 'QA'
      tags:
        description: 'Test scenario tags'

        
jobs:
  deployQA:
    if: ${{ github.event.inputs.environment == 'QA' }}
    runs-on: ubuntu-latest
    steps:
    - name: "clone dev to qa"
    - run: |
        echo "Environment: ${{ github.event.inputs.environment }} has selected"
        echo "Tags: ${{ github.event.inputs.tags }}"
        rm -rf qa
        cp -r dev qa
        
    - name: "commit and push"
    - run: |
        git config --global user.name "Hidayt Rahman"
        git config --global user.email "hidaytrahman@gmail.com"
        git pull
        git add .
        git commit -m "add files for qa"
        git push origin main
        
  deployDEV:
    if: ${{ github.event.inputs.environment == 'DEV' }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Environment: ${{ github.event.inputs.environment }} has selected"
        echo "Hidayt"
        echo "Rahman"
