name: "Manual Trigger Conditionally"

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

env: 
  LOG_LEVEL: ${{ github.event.inputs.logLevel }}
        
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
        
  printName:
    if: ${{ env.LOG_LEVEL == 'hidayt' }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hidayt"
        echo "Rahman" 
