name: "Manual Trigger Deployment"

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose Environments'     
        required: true
        default: 'QA'
      tags:
        description: 'Test scenario tags'

        
jobs:
  deployQA:
    if: ${{ github.event.inputs.environment == 'QA' }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Environment: ${{ github.event.inputs.environment }} has selected"
        echo "Tags: ${{ github.event.inputs.tags }}"
        
        
  deployDEV:
    if: ${{ github.event.inputs.environment == 'DEV' }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Environment: ${{ github.event.inputs.environment }} has selected"
        echo "Hidayt"
        echo "Rahman"
